<template><div><h1 id="打造更好用的mac终端-iterm2-zsh-ohmyzsh" tabindex="-1"><a class="header-anchor" href="#打造更好用的mac终端-iterm2-zsh-ohmyzsh"><span>打造更好用的Mac终端：iTerm2 + zsh + OhMyZsh</span></a></h1>
<p>Mac 自带的终端很简陋，缺少很多必要的功能，用户体验较差。但一个好用的终端将直接给开发人员的工作效率带来极大提升，毕竟很多操作是直接在命令行上执行的。笔者对终端有几个基本的诉求：</p>
<ul>
<li><strong>好看的界面</strong>，并包含一些<strong>关键信息</strong>，如：用户名、文件路径以及git相关信息等；</li>
<li><strong>关键字高亮</strong>，让命令行更加易读易懂；</li>
<li><strong>自动补全</strong>，根据历史命令和当前输入内容，自动推荐可能的命令。</li>
</ul>
<p>当然还有一些非必要的功能，有的话可以锦上添花，例如：</p>
<ul>
<li><strong>快速访问</strong>，快速跳转到常用目录；</li>
<li><strong>Git命令缩写</strong>，有的命令着实有点长了，能够有效的减少命令输入量；</li>
<li><strong>模糊搜索</strong>，快速搜索历史命令、文件、目录等。</li>
</ul>
<!-- more -->
<p>笔者目前的终端是基于 <strong>iTerm2 + zsh + Oh My Zsh</strong> 打造的，这套组合基本能满足上述诉求。这些工具不算新了，笔者第一份工作时mentor就给我推荐了。由于存在一定的配置成本，每次更换电脑都需要重新配置，为方便后续配置有迹可循，就有了这篇文章。</p>
<h2 id="工具介绍" tabindex="-1"><a class="header-anchor" href="#工具介绍"><span>工具介绍</span></a></h2>
<p>对本文涉及的工具进行简要介绍：</p>
<h3 id="homebrew" tabindex="-1"><a class="header-anchor" href="#homebrew"><span><a href="https://brew.sh/zh-cn/" target="_blank" rel="noopener noreferrer">Homebrew</a></span></a></h3>
<p>Mac OS 下强大的包管理工具，用来安装软件。</p>
<figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271656646.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h3 id="iterm2" tabindex="-1"><a class="header-anchor" href="#iterm2"><span><a href="https://iterm2.com/" target="_blank" rel="noopener noreferrer">iTerm2</a></span></a></h3>
<p>iTerm2是 Mac OS 终端的替代品，也是iTerm的继承者。iTerm2将终端带入了&quot;只有想不到，没有做不到&quot;的时代。</p>
<figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271704342.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h3 id="zsh" tabindex="-1"><a class="header-anchor" href="#zsh"><span><a href="https://www.zsh.org/" target="_blank" rel="noopener noreferrer">zsh</a></span></a></h3>
<p>zsh 是 shell 语言类型，兼容bash，提供强大的<strong>交互式</strong>命令行功能，比如 tab 补全，自动纠错功能等。但有一个缺点，就是配置太麻烦。下图介绍了一些常见的shell类型：</p>
<figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271717934.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h3 id="oh-my-zsh" tabindex="-1"><a class="header-anchor" href="#oh-my-zsh"><span><a href="https://ohmyz.sh/" target="_blank" rel="noopener noreferrer">Oh My Zsh</a></span></a></h3>
<p>管理 zsh 配置的框架，提供了数百个插件、主题和功能。只需要简单的修改配置文件，就能让 zsh 用的很顺手。</p>
<figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271716417.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h2 id="配置流程" tabindex="-1"><a class="header-anchor" href="#配置流程"><span>配置流程</span></a></h2>
<h3 id="第一步-安装-homebrew" tabindex="-1"><a class="header-anchor" href="#第一步-安装-homebrew"><span>第一步：安装 Homebrew</span></a></h3>
<h4 id="安装命令" tabindex="-1"><a class="header-anchor" href="#安装命令"><span>安装命令</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">/bin/bash</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -c</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>如果执行不成功，可选择国内镜像安装：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">/bin/zsh</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -c</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271838726.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h4 id="常用命令" tabindex="-1"><a class="header-anchor" href="#常用命令"><span>常用命令</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 查看配置</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 更新 Homebrew</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> update</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">#  搜索相关的包</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> search</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [关键词] </span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 查看包的信息</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> info</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [软件名]</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 查看已安装的包</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 更新某个软件</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> upgrade</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [软件名]</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 清理所有软件的旧版</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> cleanup</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 卸载某个软件</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> uninstall</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [软件名]</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 安装某个软件</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [软件名]</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 安装cask软件</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --cask</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [软件名]</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="第二步-安装-iterm-2" tabindex="-1"><a class="header-anchor" href="#第二步-安装-iterm-2"><span>第二步：安装 iTerm 2</span></a></h3>
<h4 id="安装命令-1" tabindex="-1"><a class="header-anchor" href="#安装命令-1"><span>安装命令</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> iterm2</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271841097.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h4 id="个性化设置" tabindex="-1"><a class="header-anchor" href="#个性化设置"><span>个性化设置</span></a></h4>
<p>可以在Settings中进行个性化配置，如字体、背景、快捷键等，笔者一般情况下直接使用默认配置。</p>
<figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271847191.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h3 id="第三步-安裝-zsh" tabindex="-1"><a class="header-anchor" href="#第三步-安裝-zsh"><span>第三步：安裝 zsh</span></a></h3>
<p>更多安装信息可以访问<a href="https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH" target="_blank" rel="noopener noreferrer">Installing ZSH</a>。</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> zsh</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271851444.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h3 id="第四步-安装-oh-my-zsh-并配置" tabindex="-1"><a class="header-anchor" href="#第四步-安装-oh-my-zsh-并配置"><span>第四步：安装 Oh My Zsh 并配置</span></a></h3>
<h4 id="安装命令-2" tabindex="-1"><a class="header-anchor" href="#安装命令-2"><span>安装命令</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sh</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -c</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271907948.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h4 id="个性化配置" tabindex="-1"><a class="header-anchor" href="#个性化配置"><span>个性化配置</span></a></h4>
<ul>
<li><strong>别名配置</strong></li>
</ul>
<p>oh my zsh内置了很多命令缩写别名，可执行aliases命令展示所有的别名（很多和git相关）。</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 获取所有别名</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">aliases</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">——————</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 别名列表（部分）</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ——————</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">-</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'cd -'</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">...</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">=</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">..</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">....</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">=</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">..</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.....</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">=</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">..</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">......</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">=</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">..</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">1</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'cd -1'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">2</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'cd -2'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">3</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'cd -3'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">4</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'cd -4'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">5</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'cd -5'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">6</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'cd -6'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">7</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'cd -7'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">8</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'cd -8'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">9</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'cd -9'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">_</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'sudo '</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">egrep</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'grep -E'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">fgrep</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'grep -F'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">g</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">git</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ga</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git add'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gaa</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git add --all'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gam</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git am'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gama</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git am --abort'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gamc</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git am --continue'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gams</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git am --skip'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gamscp</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git am --show-current-patch'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gap</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git apply'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gapa</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git add --patch'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gapt</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git apply --3way'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gau</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git add --update'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gav</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git add --verbose'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gb</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git branch'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbD</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git branch --delete --force'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gba</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git branch --all'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbd</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git branch --delete'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbg</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'LANG=C git branch -vv | grep ": gone\]"'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbgD</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'LANG=C git branch --no-color -vv | grep ": gone\]" | cut -c 3- | awk '</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'{print $1}'</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' | xargs git branch -D'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbgd</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'LANG=C git branch --no-color -vv | grep ": gone\]" | cut -c 3- | awk '</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'{print $1}'</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' | xargs git branch -d'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbl</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git blame -w'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbm</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git branch --move'</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">......</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">history</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">omz_history</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">l</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'ls -lah'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">la</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'ls -lAh'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ll</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'ls -lh'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ls</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'ls -G'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">lsa</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'ls -lah'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">md</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'mkdir -p'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">rd</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">rmdir</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">run-help</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">man</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">which-command</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">whence</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li><strong>主题设置</strong></li>
</ul>
<p>主题主要用于定制Zsh终端外观，默认主题为“robbyrussell”。替换方式是编辑<code v-pre>~/.zshrc</code>文件，将<code v-pre>ZSH_THEME</code>设置为对应主题。</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 编辑文件</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">vim</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ~/.zshrc</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 添加内容后执行</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">source</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> .zshrc</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271938526.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>但一些主题可能和系统默认字体不兼容，导致一些字符不能正常展示。这种情况下需要额外安装字体，笔者懒得折腾，一般就使用默认主题。下面展示agnoster和gnzh主题样式，更多样式可以到<a href="https://github.com/ohmyzsh/ohmyzsh/wiki/Themes" target="_blank" rel="noopener noreferrer">Themes</a>查看。</p>
<figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271939377.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411271942728.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>至此，<strong>好看的界面</strong>这一诉求已经达成了，其他的诉求则通过插件方式实现。</p>
<ul>
<li><strong>插件配置</strong></li>
</ul>
<p>Oh My Zsh 有几百个<a href="https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins" target="_blank" rel="noopener noreferrer">官方插件</a>，还有很多第三方插件，提供了各式各样的功能。但很多并不常用，笔者这里只推荐个人平常使用较多的插件，若对插件感兴趣可自行阅读一下相关文档。</p>
<p><strong>① git</strong></p>
<p>官方插件，默认开启。提供<strong>Git命令别名</strong>，帮助在终端中加快使用Git的速度。下面展示部分内容，查看全部别名列表可访问<a href="https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git/" target="_blank" rel="noopener noreferrer">git</a>。</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">g</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">git</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ga</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git add'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gaa</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git add --all'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gam</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git am'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gama</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git am --abort'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gamc</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git am --continue'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gams</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git am --skip'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gamscp</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git am --show-current-patch'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gap</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git apply'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gapa</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git add --patch'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gapt</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git apply --3way'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gau</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git add --update'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gav</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git add --verbose'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gb</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git branch'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbD</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git branch --delete --force'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gba</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git branch --all'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbd</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git branch --delete'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbg</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'LANG=C git branch -vv | grep ": gone\]"'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbgD</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'LANG=C git branch --no-color -vv | grep ": gone\]" | cut -c 3- | awk '</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'{print $1}'</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' | xargs git branch -D'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbgd</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'LANG=C git branch --no-color -vv | grep ": gone\]" | cut -c 3- | awk '</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'{print $1}'</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' | xargs git branch -d'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbl</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git blame -w'</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gbm</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'git branch --move'</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">......</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>② sudo</strong></p>
<p>官方插件，把<code v-pre>sudo</code> 作为当前或前一个命令的前缀，只需按两下<code v-pre>ESC</code>。通过编辑<code v-pre>~/.zshrc</code>文件，在<code v-pre>plugins</code>配置换行添加插件名即可开启。</p>
<figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411272009329.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p><strong>③ z</strong></p>
<p>官方插件，开启方式同上。跟踪最常访问的目录，能够通过输入所需目录路径中的几个字符来<strong>快速访问</strong>。</p>
<figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411272030894.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411272013222.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p><strong>④ zsh-autosuggestions</strong></p>
<p>三方插件，<strong>自动补全</strong>插件，根据历史命令和当前输入内容，自动推荐可能的命令。安装命令：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> zsh-autosuggestions</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 编辑文件</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">vim</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ~/.zshrc</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 将下面配置加到.zshrc内容末尾</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">source</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 添加内容后执行</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">source</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> .zshrc</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411272038502.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p><strong>⑤ zsh-syntax-highlighting</strong></p>
<p>三方插件，<strong>语法高亮</strong>插件，让命令行更加易读易懂。安装命令：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> zsh-syntax-highlighting</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 编辑文件</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">vim</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ~/.zshrc</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 将下面配置加到.zshrc内容末尾</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">source</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 添加内容后执行</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">source</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> .zshrc</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411272029765.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p><strong>⑥ fzf</strong></p>
<p>三方插件，<strong>模糊搜索</strong>插件，可以快速搜索历史命令、文件、目录等。安装命令：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">brew</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> fzf</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[ </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">-f</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> ~/.fzf.zsh ] &#x26;&#x26; </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">source</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ~/.fzf.zsh</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411272055083.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h2 id="结语" tabindex="-1"><a class="header-anchor" href="#结语"><span>结语</span></a></h2>
<p>上述配置后就能获得一个基本好用的终端了，但也只是基本好用，因为在AI时代，终端也需要与时俱进。iTerm2提供了与OpenAI的集成方法，但功能仅仅是用大模型辅助生成命令，能提供的帮助比较有限。</p>
<figure><img src="https://pic-bed-1256249917.cos.ap-chengdu.myqcloud.com/uPic/iterm2-ai-003-20240614205616478.gif" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>其他比较火的AI终端有<a href="https://www.warp.dev" target="_blank" rel="noopener noreferrer">warp</a>，但由于笔者还没有深入试用，下次再分享吧。warp官方做了与ITerm2的功能对比，可以先看看<a href="https://www.warp.dev/compare-terminal-tools/iterm2-vs-warp" target="_blank" rel="noopener noreferrer">iterm2-vs-warp</a>。</p>
<figure><img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202411272128581.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<div style="text-align: center;"> —— 完 —— </div>
<hr>
<p>关注“<strong>肖恩聊技术</strong>”公众号，原创技术文章第一时间推送~</p>
<img src="https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/20241103221454.png" alt="公众号二维码" width="300"></div></template>


