export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/index.html.js"), meta: {"t":"主页","i":"house"} }],
  ["/blogs/", { loader: () => import(/* webpackChunkName: "blogs_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/index.html.js"), meta: {"t":"文章","i":"pen-to-square"} }],
  ["/blogs/ai/", { loader: () => import(/* webpackChunkName: "blogs_ai_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/ai/index.html.js"), meta: {"t":"AI探索","i":"ri:speak-ai-line","O":2} }],
  ["/blogs/ai/ai-agent.html", { loader: () => import(/* webpackChunkName: "blogs_ai_ai-agent.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/ai/ai-agent.html.js"), meta: {"d":1737158400000,"l":"2025年1月18日","c":["AI探索","技术提效"],"g":["AI","智能体"],"e":"\n<p>2022年12月OpenAI推出ChatGPT，经过2023一整年迭代和各方势力追赶，在24年迎来了集体的爆发。各式各样的工具层出不穷，从最开始的聊天机器人，到AI写作工具、AI图像工具、AI视频工具、AI幻灯片工具和AI编程工具等等。好像任何和内容创作相关的场景都可以和大模型挂钩，都能产生“化学反应”。</p>\n","r":{"minutes":13.29,"words":3986},"t":"AI Agent初体验：变革正悄然发生","i":"en-to-square","y":"a"} }],
  ["/blogs/ai/ai-search.html", { loader: () => import(/* webpackChunkName: "blogs_ai_ai-search.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/ai/ai-search.html.js"), meta: {"d":1721001600000,"l":"2024年7月15日","c":["AI探索","技术提效"],"g":["AI","智能体","技术调研"],"e":"\n<p>在日常开发中，为了保证技术方案的质量，一般会在撰写前进行调研。如果先前没有相关领域的知识储备，笔者的调研方式一般是先通过搜索引擎进行关键字查询，然后再基于搜索的结果进行发散。这样调研的结果受关键字抽象程度和搜索引擎排名影响较大，可能会存在偏差导致调研不充分。刚好大模型风靡有一段时间了，就想如果AI能自动检索资料并进行内容总结，岂不美哉。避免重复造轮子，先在网上检索了一下，发现刚好有一个工具“<strong>STORM</strong>”满足诉求。</p>\n","r":{"minutes":3.52,"words":1056},"t":"用AI解锁技术调研的新姿势","i":"en-to-square","y":"a"} }],
  ["/blogs/ai/kimi.html", { loader: () => import(/* webpackChunkName: "blogs_ai_kimi.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/ai/kimi.html.js"), meta: {"d":1728691200000,"l":"2024年10月12日","c":["AI探索","技术提效"],"g":["AI","智能体","技术调研"],"e":"\n<p>如果说编程上有难题，现在第一个想到的是问GPT，一般能给出比较满意的答案，生成的代码也基本靠谱。</p>\n<p>但由于网络和中文语境要求，日常还是更多使用国内的大模型。在众多国内大模型中，笔者为何对Kimi情有独钟呢？因为我收...那必须是因为它的强项——<strong>长文本解读能力</strong>啦！</p>\n","r":{"minutes":5.53,"words":1660},"t":"我的内容创作最强搭子——Kimi","i":"en-to-square","y":"a"} }],
  ["/blogs/code-visualization/", { loader: () => import(/* webpackChunkName: "blogs_code-visualization_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/code-visualization/index.html.js"), meta: {"t":"代码可视化","i":"ant-design:code-outlined","O":4} }],
  ["/blogs/code-visualization/code-visualization-intro.html", { loader: () => import(/* webpackChunkName: "blogs_code-visualization_code-visualization-intro.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/code-visualization/code-visualization-intro.html.js"), meta: {"d":1714089600000,"l":"2024年4月26日","c":["代码可视化"],"g":["可视化","静态分析","概念引言"],"u":true,"e":"\n<blockquote>\n<p>Code visualization is the process of creating graphical representations of source code to help understand and analyze it.<br>\n代码可视化是创建源代码的图形表示以帮助理解和分析它的过程。</p>\n</blockquote>\n<p><strong>个人理解</strong>：通过使用图形化手段（架构图、依赖图、分布式追踪、类图、火焰图、CallGraph等）使代码在某些特征上变得可观测，用于辅助开发人员理解分析项目或建设一些自动化工具。</p>\n","r":{"minutes":2.73,"words":820},"t":"代码可视化(Code Visualization)","i":"en-to-square","y":"a"} }],
  ["/blogs/code-visualization/compiler.html", { loader: () => import(/* webpackChunkName: "blogs_code-visualization_compiler.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/code-visualization/compiler.html.js"), meta: {"d":1715472000000,"l":"2024年5月12日","c":["代码可视化","基础理论"],"g":["编译原理"],"e":"\n<blockquote>\n<p><a href=\"https://en.wikipedia.org/wiki/Compiler\" target=\"_blank\" rel=\"noopener noreferrer\">编译器</a>：将用编程语言(源语言)编写的计算机代码翻译成另一种语言(目标语言)的计算机程序。</p>\n</blockquote>\n<p>编译程序以高级程序源代码作为输入，以汇编语言或机器语言表示的目标程序作为输出。目标程序会在机器上运行，得到所需的结果。编译器可能执行以下操作：预处理、词法分析、语法分析、语义分析、中间代码生成、代码优化和目标代码生成。</p>\n<figure><img src=\"https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202501251345967.png\" alt=\"\" tabindex=\"0\" loading=\"lazy\"><figcaption></figcaption></figure>\n<p>编译器前端和中端理论知识与代码可视化的实现最为相关，后端部分和目标机器代码、特定机器架构相关一般很少用到可视化中。</p>\n","r":{"minutes":25.2,"words":7560},"t":"编译器前端&中端基础知识","i":"en-to-square","y":"a"} }],
  ["/blogs/code-visualization/read-code-tools.html", { loader: () => import(/* webpackChunkName: "blogs_code-visualization_read-code-tools.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/code-visualization/read-code-tools.html.js"), meta: {"d":1716681600000,"l":"2024年5月26日","c":["代码可视化","技术提效"],"g":["可视化","阅读代码"],"e":"\n<p>程序员间有句名言——“Talk is cheap, show me the code！”源码的确相较于言语更接近程序真实的状态，包含了更多的一手信息。因此，无论是刚开始学习代码的小白还是久经沙场的代码大神，不管是学习优秀的开源项目还是做老项目的重构，代码阅读都是开发者必备的技能之一。但在业务场景越来越复杂、迭代越来越快的背景下，提高梳理代码的效率能够极大程度的提高开发人员的工作效率，进一步为业务创造新的价值。</p>\n<p>工欲善其事必先利其器，阅读代码也能通过工具来提升效率，本文将介绍3种代码阅读辅助工具，大家不妨在工作中试用一下，看看是否能带来实际帮助。</p>\n","r":{"minutes":4.37,"words":1312},"t":"想提高阅读代码的效率？试试这些工具吧！","i":"en-to-square","y":"a"} }],
  ["/blogs/code-visualization/regex-vis.html", { loader: () => import(/* webpackChunkName: "blogs_code-visualization_regex-vis.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/code-visualization/regex-vis.html.js"), meta: {"d":1716681600000,"l":"2024年5月26日","c":["代码可视化","技术提效"],"g":["可视化","正则表达式","语法分析"],"e":"\n<blockquote>\n<p><a href=\"https://zh.wikipedia.org/zh-cn/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F\" target=\"_blank\" rel=\"noopener noreferrer\">正则表达式</a>是一种用来匹配字符串的强有力工具。它的设计思想是用一种描述性的语言来给字符串定义一个规则，凡是符合规则的字符串我们就认为它“匹配”了，否则该字符串就是不合法的。</p>\n</blockquote>\n<p>日常开发中常常会使用正则表达式，例如：对数据格式进行校验（判断一个字符串是否是合法的Email格式、合法的IP格式或是否按照特定格式的数字和字母拼接）；又或是将日志详情按照某种格式匹配后采集上报。复杂的正则表达式可读性很差，对地球人来说掌握比较困难，下定决心系统的学习后又会很快的忘记。在有大模型辅助编程前，如果要写一个复杂的正则表达式可能需要花费不少精力搜索资料和验证，有了大模型帮忙确实可以大大简化书写的过程。但不管是之前还是现在，可能对正则表达式执行的正确性仍不太确定（大模型也可能给出错误的结果或者由于描述不准确导致给出不符合预期的结果），这时候如果能对正则表达式可视化的分析，那么将大大增加使用的信心。</p>\n","r":{"minutes":3.93,"words":1179},"t":"看不懂正则表达式？试试可视化工具吧！","i":"en-to-square","y":"a"} }],
  ["/blogs/history/", { loader: () => import(/* webpackChunkName: "blogs_history_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/history/index.html.js"), meta: {"t":"历史考究","i":"solar:history-linear","O":5} }],
  ["/blogs/history/code-funny.html", { loader: () => import(/* webpackChunkName: "blogs_history_code-funny.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/history/code-funny.html.js"), meta: {"d":1733011200000,"l":"2024年12月1日","c":["历史考究"],"g":["编程史"],"e":"\n<p>最近干货吸收的有点多，脑子快转不动了。闲暇时搜罗了一些编程相关的趣事，放松一下。相关内容没有进行严格考证，大家图一乐就好~</p>\n","r":{"minutes":7.49,"words":2248},"t":"编程史上的趣事（一）","i":"en-to-square","y":"a"} }],
  ["/blogs/talk/2024-end.html", { loader: () => import(/* webpackChunkName: "blogs_talk_2024-end.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/talk/2024-end.html.js"), meta: {"d":1737676800000,"l":"2025年1月24日","c":["肖恩杂谈"],"g":["年度总结","个人成长"],"u":true,"e":"\n<p>若要给龙年的自己一个关键词，那非“<strong>折腾</strong>”莫属。</p>\n<p>工作上这一年达成目标，也逐渐在团队中扮演更重要的角色。家庭上喜迎迷你谢（辛苦火火妈咪），家庭读书会办了 7 场，促进了三代人（迷你谢也开始旁听了！）的关系和睦。个人上技术能力有所突破，认知也在缓慢迭代中，公众号保持住了更新频率，可喜可贺。</p>\n<p>由于个人总结很大程度上是写给自己看的，通过给记忆加一个锚点，让回顾的时候有迹可循。因此下面内容会有点流水账，大家选感兴趣的读读就好。</p>\n","r":{"minutes":8.76,"words":2629},"t":"龙年（2024）总结：折腾","i":"en-to-square","y":"a"} }],
  ["/blogs/talk/5-years-summarize.html", { loader: () => import(/* webpackChunkName: "blogs_talk_5-years-summarize.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/talk/5-years-summarize.html.js"), meta: {"d":1725667200000,"l":"2024年9月7日","c":["肖恩杂谈"],"g":["个人成长"],"e":"\n<p>工作五年了，来京东马上满一年，前四年在开水团，不禁感叹时间过的真快啊！回想19年从西安交大硕士毕业孤身前往北京开始职业生涯，经历了孤独迷茫到自立坚定，再到23年下定决心携妻还蜀安家，并来到京东开始新的征程，这5年过的很快也很充实。</p>\n<p>今年也是我的而立之年，感觉一迈过这个坎，眼前的世界就不一样了，事业上还未成气候，更多的生活琐事就开始扑面而来。网上有段子笑称现代的“五子登科”中的五子分别指的是“车子、票子、房子、妻子和孩子”，这个词本来表达的是人们对美好生活的向往，但旧词新义体现更多的是中年人的无奈。</p>\n","r":{"minutes":9.72,"words":2917},"t":"工作五年小结 | 面对不确定性快速上升的外部环境，我们该如何寻求突破？","i":"en-to-square","y":"a"} }],
  ["/blogs/talk/", { loader: () => import(/* webpackChunkName: "blogs_talk_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/talk/index.html.js"), meta: {"t":"肖恩杂谈","i":"iconoir:emoji-talking-happy","O":1} }],
  ["/blogs/talk/ip-exploration.html", { loader: () => import(/* webpackChunkName: "blogs_talk_ip-exploration.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/talk/ip-exploration.html.js"), meta: {"d":1726099200000,"l":"2024年9月12日","c":["肖恩杂谈"],"g":["个人成长","副业探索"],"e":"\n<p>现在开始探索个人IP是不是晚了？这赛道已经是一片<strong>红海</strong>了，前两年大量出现的<strong>离职博主</strong>，到如今很多也开始老老实实回去上班了。如果把个人IP当做自己的主业并想快速通过它赚米，那确实难如登天（头部效应很明显，平台可能都不会给新人多少流量）。但如果把打造IP看成一件<strong>长期的事</strong>，在维持一份基本的工作之外，不急功近利，慢慢打磨内容，降低预期后或许能得到意想不到的收获（但行好事莫问前程？<strong>食饼</strong>🤡）。</p>\n<figure><img src=\"https://cdn.jsdelivr.net/gh/Xiaoxie1994/images/images/202501251247185.png\" alt=\"\" tabindex=\"0\" loading=\"lazy\"><figcaption></figcaption></figure>","r":{"minutes":6.92,"words":2077},"t":"现在才开始探索个人IP是不是晚了？","i":"en-to-square","y":"a"} }],
  ["/blogs/tools/", { loader: () => import(/* webpackChunkName: "blogs_tools_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/tools/index.html.js"), meta: {"t":"技术提效","i":"flowbite:tools-outline","O":3} }],
  ["/blogs/tools/auto-lock.html", { loader: () => import(/* webpackChunkName: "blogs_tools_auto-lock.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/tools/auto-lock.html.js"), meta: {"d":1716681600000,"l":"2024年5月26日","c":["技术提效"],"g":["Mac","Windows","教程"],"e":"\n<p>公司要求离开工位要<strong>立刻</strong>锁定电脑屏幕防止信息泄露，但无论是使用锁屏快捷键还是设置触发角，总感觉不得劲。想想汽车现在基本都是自动锁车了，电脑它就不能自己锁屏吗？于是抽空搜罗了一些自动化的解决方案，并按照Win和Mac进行分类。</p>\n","r":{"minutes":4.43,"words":1329},"t":"离开工位老是忘记锁屏？试着让电脑自动完成这事吧！","i":"en-to-square","y":"a"} }],
  ["/blogs/tools/docker-proxy.html", { loader: () => import(/* webpackChunkName: "blogs_tools_docker-proxy.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/tools/docker-proxy.html.js"), meta: {"d":1725494400000,"l":"2024年9月5日","c":["技术提效"],"g":["Docker Hub","代理","教程"],"e":"\n<p>Docker Hub 是一个容器注册表，专为开发人员和开源贡献者构建，用于查找、使用和共享其容器镜像。但从2023年5月中旬，<a href=\"http://hub.docker.com\" target=\"_blank\" rel=\"noopener noreferrer\">hub.docker.com</a> “不知” 何种原因国内均无法正常访问了，好在国内各大高校和容器技术社区提供了加速站点，国内开发者还是能获取到各种镜像。</p>\n","r":{"minutes":1.71,"words":513},"t":"自建Docker镜像代理加速","i":"en-to-square","y":"a"} }],
  ["/blogs/tools/mac-terminal.html", { loader: () => import(/* webpackChunkName: "blogs_tools_mac-terminal.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/tools/mac-terminal.html.js"), meta: {"d":1732752000000,"l":"2024年11月28日","c":["技术提效"],"g":["Mac","终端","教程"],"e":"\n<p>Mac 自带的终端很简陋，缺少很多必要的功能，用户体验较差。但一个好用的终端将直接给开发人员的工作效率带来极大提升，毕竟很多操作是直接在命令行上执行的。笔者对终端有几个基本的诉求：</p>\n<ul>\n<li><strong>好看的界面</strong>，并包含一些<strong>关键信息</strong>，如：用户名、文件路径以及git相关信息等；</li>\n<li><strong>关键字高亮</strong>，让命令行更加易读易懂；</li>\n<li><strong>自动补全</strong>，根据历史命令和当前输入内容，自动推荐可能的命令。</li>\n</ul>\n<p>当然还有一些非必要的功能，有的话可以锦上添花，例如：</p>\n<ul>\n<li><strong>快速访问</strong>，快速跳转到常用目录；</li>\n<li><strong>Git命令缩写</strong>，有的命令着实有点长了，能够有效的减少命令输入量；</li>\n<li><strong>模糊搜索</strong>，快速搜索历史命令、文件、目录等。</li>\n</ul>\n","r":{"minutes":6.59,"words":1976},"t":"打造更好用的Mac终端","i":"en-to-square","y":"a"} }],
  ["/blogs/tools/one-cmd-web-to-app.html", { loader: () => import(/* webpackChunkName: "blogs_tools_one-cmd-web-to-app.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/tools/one-cmd-web-to-app.html.js"), meta: {"d":1727481600000,"l":"2024年9月28日","c":["技术提效"],"g":["Mac","桌面应用","教程"],"e":"\n<p>传统意义上，网站不是”用户<strong>拥有</strong>的东西“，而更像是”用户<strong>访问</strong>的地方“，具有以下特点：</p>\n<ol>\n<li><strong>用户不访问时，网站不在用户的设备上存在</strong>：这意味着网站不像应用程序那样可以安装在用户的设备上，用户不使用时，网站不会占用设备资源；</li>\n<li><strong>用户只能通过打开浏览器访问网站</strong>：用户需要主动打开浏览器，输入网址或点击链接才能访问网站；</li>\n<li><strong>高度依赖网络连接</strong>：网站需要网络连接才能访问，如果用户没有网络，就无法访问网站。</li>\n</ol>\n<p>但如果我们发现了一个有意思的网站，想拥有它，这时就不希望它是传统意义上的网站了，更希望是一个原生的APP。这样当我们使用时，点击一个图标即可打开，提供沉浸式的用户体验。</p>\n","r":{"minutes":4.16,"words":1248},"t":"用一行命令把任意网站变成桌面应用","i":"en-to-square","y":"a"} }],
  ["/blogs/tools/picture-manage.html", { loader: () => import(/* webpackChunkName: "blogs_tools_picture-manage.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/blogs/tools/picture-manage.html.js"), meta: {"d":1732320000000,"l":"2024年11月23日","c":["技术提效"],"g":["图床","自动化","写作工具","教程"],"e":"\n<p>笔者在<a href=\"https://mp.weixin.qq.com/s/HDUjesD7Qs5o9qm3bPs_ZA\" target=\"_blank\" rel=\"noopener noreferrer\">我的内容创作最强搭子——Kimi</a>中介绍了周刊创作时素材收集和整理的基本思路，这之后便会进行文章撰写。</p>\n<p>写作在电脑本地进行，采用 <a href=\"https://www.markdownguide.org\" target=\"_blank\" rel=\"noopener noreferrer\">Markdown</a> 语法，不过其有一个缺点——<strong>不能所见即所得</strong>。因此需要一个专业的 Markdown 写作编辑器来展示效果，笔者目前使用双链笔记工具 Obsidian。</p>\n<p>另外本地写作使用 Markdown 时还有一个痛点——<strong>图片管理困难</strong>。图片粘贴后默认存放到本地目录下，如果路径进行了变更还需要手动调整图片的引用。前期周刊写完后还需要一一检查图片的引用，相当的痛苦，这对写作意愿有不小的消耗。</p>\n<p>针对上述第二个痛点，本文将介绍一种图片管理方案，不花一分钱即可实现文章图片自动管理，做到“<strong>一次写作，到处（粘贴）发布</strong>”。</p>\n","r":{"minutes":3.92,"words":1175},"t":"文章图片自动管理方案","i":"en-to-square","y":"a"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/404.html.js"), meta: {"t":""} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"t":"分类","I":false} }],
  ["/category/ai%E6%8E%A2%E7%B4%A2/", { loader: () => import(/* webpackChunkName: "category_ai探索_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/category/ai探索/index.html.js"), meta: {"t":"AI探索 分类","I":false} }],
  ["/category/%E6%8A%80%E6%9C%AF%E6%8F%90%E6%95%88/", { loader: () => import(/* webpackChunkName: "category_技术提效_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/category/技术提效/index.html.js"), meta: {"t":"技术提效 分类","I":false} }],
  ["/category/%E4%BB%A3%E7%A0%81%E5%8F%AF%E8%A7%86%E5%8C%96/", { loader: () => import(/* webpackChunkName: "category_代码可视化_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/category/代码可视化/index.html.js"), meta: {"t":"代码可视化 分类","I":false} }],
  ["/category/%E5%9F%BA%E7%A1%80%E7%90%86%E8%AE%BA/", { loader: () => import(/* webpackChunkName: "category_基础理论_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/category/基础理论/index.html.js"), meta: {"t":"基础理论 分类","I":false} }],
  ["/category/%E5%8E%86%E5%8F%B2%E8%80%83%E7%A9%B6/", { loader: () => import(/* webpackChunkName: "category_历史考究_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/category/历史考究/index.html.js"), meta: {"t":"历史考究 分类","I":false} }],
  ["/category/%E8%82%96%E6%81%A9%E6%9D%82%E8%B0%88/", { loader: () => import(/* webpackChunkName: "category_肖恩杂谈_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/category/肖恩杂谈/index.html.js"), meta: {"t":"肖恩杂谈 分类","I":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"t":"标签","I":false} }],
  ["/tag/ai/", { loader: () => import(/* webpackChunkName: "tag_ai_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/ai/index.html.js"), meta: {"t":"标签: AI","I":false} }],
  ["/tag/%E6%99%BA%E8%83%BD%E4%BD%93/", { loader: () => import(/* webpackChunkName: "tag_智能体_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/智能体/index.html.js"), meta: {"t":"标签: 智能体","I":false} }],
  ["/tag/%E6%8A%80%E6%9C%AF%E8%B0%83%E7%A0%94/", { loader: () => import(/* webpackChunkName: "tag_技术调研_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/技术调研/index.html.js"), meta: {"t":"标签: 技术调研","I":false} }],
  ["/tag/%E5%8F%AF%E8%A7%86%E5%8C%96/", { loader: () => import(/* webpackChunkName: "tag_可视化_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/可视化/index.html.js"), meta: {"t":"标签: 可视化","I":false} }],
  ["/tag/%E9%9D%99%E6%80%81%E5%88%86%E6%9E%90/", { loader: () => import(/* webpackChunkName: "tag_静态分析_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/静态分析/index.html.js"), meta: {"t":"标签: 静态分析","I":false} }],
  ["/tag/%E6%A6%82%E5%BF%B5%E5%BC%95%E8%A8%80/", { loader: () => import(/* webpackChunkName: "tag_概念引言_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/概念引言/index.html.js"), meta: {"t":"标签: 概念引言","I":false} }],
  ["/tag/%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86/", { loader: () => import(/* webpackChunkName: "tag_编译原理_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/编译原理/index.html.js"), meta: {"t":"标签: 编译原理","I":false} }],
  ["/tag/%E9%98%85%E8%AF%BB%E4%BB%A3%E7%A0%81/", { loader: () => import(/* webpackChunkName: "tag_阅读代码_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/阅读代码/index.html.js"), meta: {"t":"标签: 阅读代码","I":false} }],
  ["/tag/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F/", { loader: () => import(/* webpackChunkName: "tag_正则表达式_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/正则表达式/index.html.js"), meta: {"t":"标签: 正则表达式","I":false} }],
  ["/tag/%E8%AF%AD%E6%B3%95%E5%88%86%E6%9E%90/", { loader: () => import(/* webpackChunkName: "tag_语法分析_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/语法分析/index.html.js"), meta: {"t":"标签: 语法分析","I":false} }],
  ["/tag/%E7%BC%96%E7%A8%8B%E5%8F%B2/", { loader: () => import(/* webpackChunkName: "tag_编程史_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/编程史/index.html.js"), meta: {"t":"标签: 编程史","I":false} }],
  ["/tag/%E5%B9%B4%E5%BA%A6%E6%80%BB%E7%BB%93/", { loader: () => import(/* webpackChunkName: "tag_年度总结_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/年度总结/index.html.js"), meta: {"t":"标签: 年度总结","I":false} }],
  ["/tag/%E4%B8%AA%E4%BA%BA%E6%88%90%E9%95%BF/", { loader: () => import(/* webpackChunkName: "tag_个人成长_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/个人成长/index.html.js"), meta: {"t":"标签: 个人成长","I":false} }],
  ["/tag/%E5%89%AF%E4%B8%9A%E6%8E%A2%E7%B4%A2/", { loader: () => import(/* webpackChunkName: "tag_副业探索_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/副业探索/index.html.js"), meta: {"t":"标签: 副业探索","I":false} }],
  ["/tag/mac/", { loader: () => import(/* webpackChunkName: "tag_mac_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/mac/index.html.js"), meta: {"t":"标签: Mac","I":false} }],
  ["/tag/windows/", { loader: () => import(/* webpackChunkName: "tag_windows_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/windows/index.html.js"), meta: {"t":"标签: Windows","I":false} }],
  ["/tag/%E6%95%99%E7%A8%8B/", { loader: () => import(/* webpackChunkName: "tag_教程_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/教程/index.html.js"), meta: {"t":"标签: 教程","I":false} }],
  ["/tag/docker-hub/", { loader: () => import(/* webpackChunkName: "tag_docker-hub_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/docker-hub/index.html.js"), meta: {"t":"标签: Docker Hub","I":false} }],
  ["/tag/%E4%BB%A3%E7%90%86/", { loader: () => import(/* webpackChunkName: "tag_代理_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/代理/index.html.js"), meta: {"t":"标签: 代理","I":false} }],
  ["/tag/%E7%BB%88%E7%AB%AF/", { loader: () => import(/* webpackChunkName: "tag_终端_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/终端/index.html.js"), meta: {"t":"标签: 终端","I":false} }],
  ["/tag/%E6%A1%8C%E9%9D%A2%E5%BA%94%E7%94%A8/", { loader: () => import(/* webpackChunkName: "tag_桌面应用_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/桌面应用/index.html.js"), meta: {"t":"标签: 桌面应用","I":false} }],
  ["/tag/%E5%9B%BE%E5%BA%8A/", { loader: () => import(/* webpackChunkName: "tag_图床_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/图床/index.html.js"), meta: {"t":"标签: 图床","I":false} }],
  ["/tag/%E8%87%AA%E5%8A%A8%E5%8C%96/", { loader: () => import(/* webpackChunkName: "tag_自动化_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/自动化/index.html.js"), meta: {"t":"标签: 自动化","I":false} }],
  ["/tag/%E5%86%99%E4%BD%9C%E5%B7%A5%E5%85%B7/", { loader: () => import(/* webpackChunkName: "tag_写作工具_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/tag/写作工具/index.html.js"), meta: {"t":"标签: 写作工具","I":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"t":"文章","I":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"t":"星标","I":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"/Users/shawn/Documents/GitHub/suibi/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"t":"时间轴","I":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
